### ISSUE TITLE
Handle draws

### ISSUE THREAD

**Issue by kiriDevs** [KulaJunke/Tic-Tac-Toe#2]
## What happens?
Currently, when there is a draw, the game continues to ask player 1 for a move (since they can't make any valid move).

## What is supposed to happen?
Maybe a message could tell the players that the game ended in a draw.

## Further information
- You could easily check for draws by checking if none of the cells on the board is -1 anymore, even though no player has won the game yet.
- I have attached an image to this issue showing how the game currently doesn't handle draws as expected.

![image](https://user-images.githubusercontent.com/56218513/114110379-aba46380-98d7-11eb-854f-d7e85e8f4ec3.png)

**Comment by KulaJunke** [comment]
I know. Going to fix it later.

**Comment by kiriDevs** [comment]
Seems to have been fixed by 5a8ab0bfa809cab2871381d83dcd87f4d986b26c, closing.
